print("What is the name of the gift giver?")
name = raw_input()
print("What is the present they gave you?")
present = raw_input()
print("How old were you on your birthday?")
age = int(raw_input())
print("What is your name?")
yourName = raw_input()
print("Dear " + name + ", ")
print("")
print("Thank you for the " + present + ". ")
print("I really like it. I can't believe ")
print("I am already " + str(age) + " years old, but ")
print("it does not feel much different than being ")
print(str(age-1) + ".")
print("")
print("Sincerely,")
print("")
print(yourName)